-- Schema Migration for INPUNJABMASTER Admin Panel & Tracking

-- 1. Extend public.articles
ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS author text DEFAULT 'Admin',
ADD COLUMN IF NOT EXISTS sub_headline text,
ADD COLUMN IF NOT EXISTS region text DEFAULT 'Punjab',
ADD COLUMN IF NOT EXISTS seo_title text,
ADD COLUMN IF NOT EXISTS meta_description text,
ADD COLUMN IF NOT EXISTS slug text,
ADD COLUMN IF NOT EXISTS status text DEFAULT 'published';

-- 2. Create public.comments
CREATE TABLE IF NOT EXISTS public.comments (
    id bigint generated by default as identity primary key,
    article_id bigint references public.articles(id) on delete cascade,
    author_name text not null,
    content text not null,
    status text default 'pending', -- pending, approved, flagged, spam
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create public.subscribers
CREATE TABLE IF NOT EXISTS public.subscribers (
    id bigint generated by default as identity primary key,
    email text unique not null,
    status text default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create public.tickers
CREATE TABLE IF NOT EXISTS public.tickers (
    id bigint generated by default as identity primary key,
    headline text not null,
    link text,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Create public.ads
CREATE TABLE IF NOT EXISTS public.ads (
    id bigint generated by default as identity primary key,
    slot text not null,
    client text not null,
    image_url text not null,
    link text,
    clicks integer default 0,
    status text default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Setup Row Level Security (RLS) policies for ALL CRUD via public (anon)
-- ARTICLES
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read All Articles" ON public.articles;
DROP POLICY IF EXISTS "Public Insert Articles" ON public.articles;
DROP POLICY IF EXISTS "Public Update Articles" ON public.articles;
DROP POLICY IF EXISTS "Public Delete Articles" ON public.articles;
CREATE POLICY "Public Read All Articles" ON public.articles FOR SELECT USING (true);
CREATE POLICY "Public Insert Articles" ON public.articles FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Articles" ON public.articles FOR UPDATE USING (true);
CREATE POLICY "Public Delete Articles" ON public.articles FOR DELETE USING (true);

-- CATEGORIES
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read All Categories" ON public.categories;
DROP POLICY IF EXISTS "Public Insert Categories" ON public.categories;
DROP POLICY IF EXISTS "Public Update Categories" ON public.categories;
DROP POLICY IF EXISTS "Public Delete Categories" ON public.categories;
CREATE POLICY "Public Read All Categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public Insert Categories" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Categories" ON public.categories FOR UPDATE USING (true);
CREATE POLICY "Public Delete Categories" ON public.categories FOR DELETE USING (true);

-- COMMENTS
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read All Comments" ON public.comments FOR SELECT USING (true);
CREATE POLICY "Public Insert Comments" ON public.comments FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Comments" ON public.comments FOR UPDATE USING (true);
CREATE POLICY "Public Delete Comments" ON public.comments FOR DELETE USING (true);

-- SUBSCRIBERS
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read All Subscribers" ON public.subscribers FOR SELECT USING (true);
CREATE POLICY "Public Insert Subscribers" ON public.subscribers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Subscribers" ON public.subscribers FOR UPDATE USING (true);
CREATE POLICY "Public Delete Subscribers" ON public.subscribers FOR DELETE USING (true);

-- TICKERS
ALTER TABLE public.tickers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read All Tickers" ON public.tickers FOR SELECT USING (true);
CREATE POLICY "Public Insert Tickers" ON public.tickers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Tickers" ON public.tickers FOR UPDATE USING (true);
CREATE POLICY "Public Delete Tickers" ON public.tickers FOR DELETE USING (true);

-- ADS
ALTER TABLE public.ads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read All Ads" ON public.ads FOR SELECT USING (true);
CREATE POLICY "Public Insert Ads" ON public.ads FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Ads" ON public.ads FOR UPDATE USING (true);
CREATE POLICY "Public Delete Ads" ON public.ads FOR DELETE USING (true);

-- 7. RPC Function to atomically increment view count
CREATE OR REPLACE FUNCTION increment_view_count(article_id bigint)
RETURNS void AS $$
BEGIN
  UPDATE public.articles
  SET view_count = coalesce(view_count, 0) + 1
  WHERE id = article_id;
END;
$$ LANGUAGE plpgsql;

-- 8. RPC Function to atomically increment ad clicks
CREATE OR REPLACE FUNCTION increment_ad_clicks(ad_id bigint)
RETURNS void AS $$
BEGIN
  UPDATE public.ads
  SET clicks = coalesce(clicks, 0) + 1
  WHERE id = ad_id;
END;
$$ LANGUAGE plpgsql;

-- Initial Seed Data for Tickers
INSERT INTO public.tickers (headline, link) VALUES 
('LATEST: Punjab Government announces new agricultural subsidies.', '#'),
('BREAKING: Major highway inaugurated connecting rural districts.', '#');
